var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';
OA_output['Sidebar 1'] += "<"+"span class=\"declare\">Advertisement<"+"/span><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4773__zoneid=40__OXLCA=1__cb=08875edbeb__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sidebar%29%26utm_medium%3Dbanner%26utm_content%3DDesign%252BHow%252BYou%252BWant%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=design-black-190x400_6.png&contenttype=png\' width=\'190\' height=\'400\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_08875edbeb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4773&amp;campaignid=1695&amp;zoneid=40&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=08875edbeb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"div id=\'ox_72421647288a694363d1455fdaff72cd\' style=\'display: inline;\'><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4834__zoneid=22__OXLCA=1__cb=49a3d070bb__oadest=http%3A%2F%2Fwww.mindmaple.com%2FProducts%2FWindows%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=cnet_banner_300x250_(1).jpg&contenttype=swf\' width=\'300\' height=\'250\' alt=\'MindMaple - Your Tree Of Ideas\' title=\'MindMaple - Your Tree Of Ideas\' border=\'0\' /><"+"/a><"+"/div>\n";
OA_output['Medium Rectangle'] += "<"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['Medium Rectangle'] += "var ox_swf = new FlashObject(\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=d9427e592d852756c2673cb3787b6ba3_4.swf&contenttype=swf\', \'MindMaple - Your Tree Of Ideas\', \'300\', \'250\', \'10\');\n";
OA_output['Medium Rectangle'] += "ox_swf.addVariable(\'alink1\', \'http%3A%2F%2Fauslieferung.commindo-media-ressourcen.de%2Fwww%2Fdelivery%2Fck.php%3Foaparams%3D2__bannerid%3D4834__zoneid%3D22__OXLCA%3D1__cb%3D49a3d070bb__oadest%3Dhttp%253A%252F%252Fwww.mindmaple.com%252FProducts%252FWindows%252F\');\n";
OA_output['Medium Rectangle'] += "ox_swf.addVariable(\'atar1\', \'_blank\');\n";
OA_output['Medium Rectangle'] += "ox_swf.addParam(\'wmode\',\'transparent\');\n";
OA_output['Medium Rectangle'] += "ox_swf.addParam(\'allowScriptAccess\',\'always\');\n";
OA_output['Medium Rectangle'] += "ox_swf.write(\'ox_72421647288a694363d1455fdaff72cd\');\n";
OA_output['Medium Rectangle'] += "if (ox_swf.installedVer.versionIsValid(ox_swf.getAttribute(\'version\'))) { document.write(\"<"+"div id=\'beacon_49a3d070bb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4834&amp;campaignid=1719&amp;zoneid=22&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=49a3d070bb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\"); } else { document.write(\"<"+"div id=\'beacon_49a3d070bb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4834&amp;campaignid=1719&amp;zoneid=22&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;oxfb=1&amp;cb=49a3d070bb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\"); }\n";
OA_output['Medium Rectangle'] += "// ]]> --><"+"/script><"+"noscript><"+"div id=\'beacon_49a3d070bb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4834&amp;campaignid=1719&amp;zoneid=22&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;oxfb=1&amp;cb=49a3d070bb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/noscript>\n";
OA_output['Comment spnsr'] = '';
OA_output['Comment spnsr'] += "<"+"style type=\"text/css\">\n";
OA_output['Comment spnsr'] += "div div.singlepost.advertisement span.declare {\n";
OA_output['Comment spnsr'] += "display: none;\n";
OA_output['Comment spnsr'] += "}\n";
OA_output['Comment spnsr'] += "<"+"/style><"+"style type=\"text/css\">.comment-job-board { margin: 2em 6% 2em 0; background: #FEFED3; padding: 1.25em 1em;	overflow: hidden; font: 1.2em/1.4em \"Skolar Bold\", Georgia, serif; }.comment-job-board a {display: block;color: #000;}.comment-job-board a span {padding-top:0.75em;display: block;font: 0.8em/1.4em \"Proxima Nova Regular\", Arial, sans-serif;}.comment-job-board a:focus, .comment-job-board a:active {background-color: transparent;}.comment-job-board img {float: right;margin: 0 0 0em 1em;}<"+"/style>\n";
OA_output['Comment spnsr'] += "<"+"div class=\"comment-job-board\"><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4551__zoneid=26__OXLCA=1__cb=ba28200d33__oadest=http%3A%2F%2Fjobs.smashingmagazine.com%2F%3Futm_source%3Dsm%26utm_medium%3Dtextad%26utm_campaign%3Dinternal\" target=\"_self\"><"+"img src=\"http://www.smashingmagazine.com/wp-content/uploads/2012/01/job-board-transparent.gif\" style=\"border-radius: 5px; border: 1px solid rgba(0,0,0,0.05); padding: 7px; background-color: #fff; max-width: 95px !important;\" width=\"95\" />Post your job listing in our Job Board!<"+"span>If you\'re looking for a job or have a job opening to announce, post it in our job board and get noticed by professionals and well-respected companies. <"+"b style=\"text-decoration: underline;font-family: Proxima Nova Bold, Proxima Nova, Arial\">Submit a job listing<"+"/b>, and good luck!<"+"/span><"+"/a><"+"/div><"+"div id=\'beacon_ba28200d33\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4551&amp;campaignid=1593&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;cb=ba28200d33\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Logo'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\">(<"+"strong>Smashing\'s side note<"+"/strong>: Have you already pre-ordered the brand new <"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3452__zoneid=68__OXLCA=1__cb=335b7e4919__oadest=http%3A%2F%2Fwww.smashingmagazine.com%2F2012%2F10%2F16%2Fthe-mobile-book-preorder%2F\" style=\"border-bottom: 1px solid rgba(0,0,0,0.1)\" >Smashing Mobile Book<"+"/a>? The book features everything you need to know as a designer or developer to create beautiful and rich mobile experiences. <"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3452__zoneid=68__OXLCA=1__cb=335b7e4919__oadest=http%3A%2F%2Fwww.smashingmagazine.com%2F2012%2F10%2F16%2Fthe-mobile-book-preorder%2Fhttp%3A%2F%2Fwww.the-mobile-book.com\" target=\"_self\">Get your book today!<"+"/a>)<"+"div id=\'beacon_335b7e4919\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3452&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;cb=335b7e4919\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Sidebar Special'] = '';
OA_output['Sidebar Special'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4777__zoneid=72__OXLCA=1__cb=3137a2560a__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28420x200%29%26utm_medium%3Dbanner%26utm_content%3DDesign%252BHow%252BYou%252BWant%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=design-black-420x200_6.png&contenttype=png\' width=\'420\' height=\'200\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_3137a2560a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4777&amp;campaignid=1696&amp;zoneid=72&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=3137a2560a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';
OA_output['VIS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=c4fe8c130a__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_w3m_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'PSD to HTML\' title=\'PSD to HTML\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=c4fe8c130a__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'>PSD to HTML<"+"/a><"+"div id=\'beacon_c4fe8c130a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4360&amp;campaignid=135&amp;zoneid=70&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=c4fe8c130a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4732__zoneid=24__OXLCA=1__cb=7e52b08feb__oadest=http%3A%2F%2Fwww.psd2html.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=p2h_200x125-1.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4732__zoneid=24__OXLCA=1__cb=7e52b08feb__oadest=http%3A%2F%2Fwww.psd2html.com%2F\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_7e52b08feb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4732&amp;campaignid=1626&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=7e52b08feb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3738__zoneid=24__OXLCA=1__cb=9c94bcb553__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200roshlp\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_cirlcles_new.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Create free stunning websites!\' title=\'Create free stunning websites!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3738__zoneid=24__OXLCA=1__cb=9c94bcb553__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200roshlp\' target=\'_blank\'>Create free stunning sites!<"+"/a><"+"div id=\'beacon_9c94bcb553\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3738&amp;campaignid=130&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=9c94bcb553\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=f8c69a6fe4__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-dt-2.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Premium Web Templates\' title=\'Premium Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=f8c69a6fe4__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'>Premium Web Templates<"+"/a><"+"div id=\'beacon_f8c69a6fe4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=2877&amp;campaignid=1026&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=f8c69a6fe4\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4781__zoneid=24__OXLCA=1__cb=0f97a7ba80__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DCreate%252BWebsites%252Bin%252Bthe%252BCloud%252B%28White%29%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=cloud-create-white-200x125_13.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Sign Up for Free\' title=\'Sign Up for Free\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4781__zoneid=24__OXLCA=1__cb=0f97a7ba80__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DCreate%252BWebsites%252Bin%252Bthe%252BCloud%252B%28White%29%26utm_campaign%3DSmashing\' target=\'_blank\'>Sign Up for Free<"+"/a><"+"div id=\'beacon_0f97a7ba80\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4781&amp;campaignid=1697&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=0f97a7ba80\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4828__zoneid=24__OXLCA=1__cb=cb0ebc6161__oadest=http%3A%2F%2Fteamtreehouse.com%2Fjoin%2Ffree-month%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmashing-magazine%26utm_content%3D200x125-black%26cid%3D1043\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_learn_dev_design-new_3.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Learn HTML5, CSS3, UX and more\' title=\'Learn HTML5, CSS3, UX and more\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4828__zoneid=24__OXLCA=1__cb=cb0ebc6161__oadest=http%3A%2F%2Fteamtreehouse.com%2Fjoin%2Ffree-month%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmashing-magazine%26utm_content%3D200x125-black%26cid%3D1043\' target=\'_blank\'>Learn HTML5, CSS3, UX and more<"+"/a><"+"div id=\'beacon_cb0ebc6161\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4828&amp;campaignid=1715&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=cb0ebc6161\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"div style=\"display:none\">\n";
OA_output['spnsr ROS 5'] += "<"+"!-- Google Code for Smashing Magazine Users -->\n";
OA_output['spnsr ROS 5'] += "<"+"script type=\"text/javascript\">\n";
OA_output['spnsr ROS 5'] += "/* <"+"![CDATA[ */\n";
OA_output['spnsr ROS 5'] += "var google_conversion_id = 1017883234;\n";
OA_output['spnsr ROS 5'] += "var google_conversion_label = \"neTrCM6DyAMQ4tSu5QM\";\n";
OA_output['spnsr ROS 5'] += "var google_custom_params = window.google_tag_params;\n";
OA_output['spnsr ROS 5'] += "var google_remarketing_only = true;\n";
OA_output['spnsr ROS 5'] += "/* ]]> */\n";
OA_output['spnsr ROS 5'] += "<"+"/script>\n";
OA_output['spnsr ROS 5'] += "<"+"script type=\"text/javascript\" src=\"//www.googleadservices.com/pagead/conversion.js\">\n";
OA_output['spnsr ROS 5'] += "<"+"/script>\n";
OA_output['spnsr ROS 5'] += "<"+"noscript>\n";
OA_output['spnsr ROS 5'] += "<"+"div style=\"display:inline;\">\n";
OA_output['spnsr ROS 5'] += "<"+"img height=\"1\" width=\"1\" style=\"border-style:none;\" alt=\"\" src=\"//googleads.g.doubleclick.net/pagead/viewthroughconversion/1017883234/?value=0&amp;label=neTrCM6DyAMQ4tSu5QM&amp;guid=ON&amp;script=0\"/>\n";
OA_output['spnsr ROS 5'] += "<"+"/div>\n";
OA_output['spnsr ROS 5'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 5'] += "<"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=6fc3dae29e__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_ms_smashing.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=6fc3dae29e__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'>PSD to HTML5/CSS3<"+"/a><"+"div id=\'beacon_6fc3dae29e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4588&amp;campaignid=1625&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=6fc3dae29e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4878__zoneid=24__OXLCA=1__cb=26ab6b96c8__oadest=http%3A%2F%2Fwww.zoho.com%2Fsites%2Ffree-website-builder.html%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_content%3Dfree-website%26utm_campaign%3Dsmashing-magazine\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=fw_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Free Websites\' title=\'Free Websites\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4878__zoneid=24__OXLCA=1__cb=26ab6b96c8__oadest=http%3A%2F%2Fwww.zoho.com%2Fsites%2Ffree-website-builder.html%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_content%3Dfree-website%26utm_campaign%3Dsmashing-magazine\' target=\'_blank\'>Free Websites<"+"/a><"+"div id=\'beacon_26ab6b96c8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4878&amp;campaignid=1735&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=26ab6b96c8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"script language=\"JavaScript\" type=\"text/javascript\" src=\"http://view.atdmt.com/SHS/jview/348574350/direct/01?click=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4572__zoneid=24__OXLCA=1__cb=825c88d637__oadest=\">\n";
OA_output['spnsr ROS 8'] += "<"+"/script><"+"noscript><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4572__zoneid=24__OXLCA=1__cb=825c88d637__oadest=http%3A%2F%2Fclk.atdmt.com%2FSHS%2Fgo%2F348574350%2Fdirect%2F01%2F\" target=\"_blank\"><"+"img border=\"0\" src=\"http://view.atdmt.com/SHS/view/348574350/direct/01/\" /><"+"/a><"+"/noscript>\n";
OA_output['spnsr ROS 8'] += "<"+"br>\n";
OA_output['spnsr ROS 8'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4572__zoneid=24__OXLCA=1__cb=825c88d637__oadest=http%3A%2F%2Fwww.shutterstock.com%2F%3Fsid%3DSMSHM1004%26pl%3Dsmashingmagazine-200x125%26utm_medium%3Dtext_link\" target=\"_blank\">Royalty-Free Stock Images<"+"/a><"+"div id=\'beacon_825c88d637\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4572&amp;campaignid=1608&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;cb=825c88d637\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4538__zoneid=24__OXLCA=1__cb=9a65d23b39__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=project-mgt(200x125)_15.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4538__zoneid=24__OXLCA=1__cb=9a65d23b39__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_9a65d23b39\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4538&amp;campaignid=1587&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=9a65d23b39\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4835__zoneid=24__OXLCA=1__cb=302e78b480__oadest=http%3A%2F%2Fwww.mindmaple.com%2FProducts%2FWindows%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=mindmaple_smashingmagazine_200x125_3.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4835__zoneid=24__OXLCA=1__cb=302e78b480__oadest=http%3A%2F%2Fwww.mindmaple.com%2FProducts%2FWindows%2F\' target=\'_blank\'>MindMaple - Your Tree of Ideas<"+"/a><"+"div id=\'beacon_302e78b480\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4835&amp;campaignid=1720&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=302e78b480\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4820__zoneid=24__OXLCA=1__cb=fecf3afd17__oadest=http%3A%2F%2Fignitemobi.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=magazinead_small.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Need A Mobile Site? Easy!\' title=\'Need A Mobile Site? Easy!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4820__zoneid=24__OXLCA=1__cb=fecf3afd17__oadest=http%3A%2F%2Fignitemobi.com%2F\' target=\'_blank\'>Need A Mobile Site? Easy!<"+"/a><"+"div id=\'beacon_fecf3afd17\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4820&amp;campaignid=1710&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=fecf3afd17\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4877__zoneid=24__OXLCA=1__cb=52c930b82c__oadest=http%3A%2F%2Fwww.elegantbanner.com%2F\" target=\"_blank\"><"+"img src=\"http://www.elegantbanner.com/home/elegantbanner200x125.png\"/><"+"/a>\n";
OA_output['spnsr ROS 12'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4877__zoneid=24__OXLCA=1__cb=52c930b82c__oadest=http%3A%2F%2Fwww.elegantbanner.com%2F\" target=\"_blank\">Beautiful Web Banners<"+"/a><"+"div id=\'beacon_52c930b82c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4877&amp;campaignid=1734&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;cb=52c930b82c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4807__zoneid=24__OXLCA=1__cb=e1683296e7__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=typekit-ad-200x125-1_14.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Web fonts with Typekit\' title=\'Web fonts with Typekit\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4807__zoneid=24__OXLCA=1__cb=e1683296e7__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'>Web fonts with Typekit<"+"/a><"+"div id=\'beacon_e1683296e7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4807&amp;campaignid=1704&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=e1683296e7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3739__zoneid=24__OXLCA=1__cb=8a9e449490__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200cpchlp\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_cirlcles_new_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Create free stunning websites!\' title=\'Create free stunning websites!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3739__zoneid=24__OXLCA=1__cb=8a9e449490__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200cpchlp\' target=\'_blank\'>Create free stunning sites!<"+"/a><"+"div id=\'beacon_8a9e449490\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3739&amp;campaignid=250&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=8a9e449490\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4850__zoneid=24__OXLCA=1__cb=c2d0c1a44a__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smashingnoupebanner6a_4.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4850__zoneid=24__OXLCA=1__cb=c2d0c1a44a__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_c2d0c1a44a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4850&amp;campaignid=1729&amp;zoneid=24&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=c2d0c1a44a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';

OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4726__zoneid=77__OXLCA=1__cb=fe21e59dff__oadest=http%3A%2F%2Fad.au.doubleclick.net%2Fclk%3B264175606%3B89718897%3Bh%3Fhttp%3A%2F%2Fwww.squarespace.com%2Fapi%2Ftrack%2FRedirect%3Furl%3D%2F%26channel%3Ddisplay%26subchannel%3Dsmashing%26source%3Dros%26campaign%3D410x125\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=410x125-4.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_fe21e59dff\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4726&amp;campaignid=1676&amp;zoneid=77&amp;loc=http%3A%2F%2Fmobile.smashingmagazine.com%2F2010%2F07%2F19%2Fhow-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website%2F&amp;referer=http%3A%2F%2Fwww.webdesigndev.com%2Fweb-development%2Fresponsive-web-design-tutorials&amp;cb=fe21e59dff\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';

OA_output['Sponsor XXL 3'] = '';

OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

OA_output['Specials'] = '';

